name: sigma_trips
description: Sigma Trips webview app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

flutter:
  uses-material-design: true
